namespace MoveMate.Domain.Enums;

public enum TrackerEnums
{
    PENDING,
    REPORT,
    REVIEW_OFFLINE,
    DRIVER_ARRIVED,
    DRIVER_COMPLETED,
    PORTER_ARRIVED,
    PORTER_PACKING,
    PORTER_DELIVERED,
    PORTER_UNLOADEDED,
    PORTER_COMPLETED
}