name: CD

on:
  push:
    branches: main

jobs:
  build:
    name: build move-mate
    runs-on: ubuntu-latest
    steps:
#      - name: Clear useless artifacts
#        uses: c-hive/gha-remove-artifacts@v1.2.0
#        with:
#          age: '14 days'

      - uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./MoveMate.API/MoveMate.API.csproj

      - name: Build
        run: dotnet build ./MoveMate.API/MoveMate.API.csproj --configuration Release --no-restore

      - name: Publish .NET Application
        run: |
          dotnet publish ./MoveMate.API/MoveMate.API.csproj --configuration Release --output ./publish

      - name: Create and Zip the Site
        run: |
          cd ./publish
          zip -r ../site.zip *

      - name: Upload Zip to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: site.zip

  deploy:
    needs: build
    name: deploy move-mate
    runs-on: self-hosted
    steps:
      - name: Clone source zip
        uses: actions/download-artifact@v3
        with:
          name: move-mate
      - name: Deploy to IIS
        shell: powershell
        run: |
          iisreset /stop
          Remove-Item -Recurse -Force -Confirm:$false C:\inetpub\wwwroot\MoveMate-API\
          mkdir C:\inetpub\wwwroot\MoveMate-API
          Expand-Archive site.zip C:\inetpub\wwwroot\MoveMate-API
          iisreset /start
